#!/usr/bin/env node
// audit-queue.mjs — (re)generate .agent/checklists/AUDIT_STATUS.md
//
// Builds a RISK-ORDERED audit queue so the loop spends its budget where it
// matters most. Risk score per component:
//   + reference spec page exists (.agent/references/spec/<Name>.dc.html)   (×3)
//   + how many other components import it (blast radius)                   (×1..2)
//   + static triage severity from verify-audit.mjs                         (×1..2)
// Ordering: highest risk first; ties break on import count.
//
// Preserves existing audit results: rows already marked reviewed keep their
// status (parsed back from the current AUDIT_STATUS.md if present).
//
// Usage: node .agent/scripts/audit-queue.mjs   (writes the tracker, prints summary)

import { readFileSync, readdirSync, existsSync, writeFileSync } from "node:fs"
import { execSync } from "node:child_process"
import { join } from "node:path"

const UI = "src/components/ui"
const SPEC = ".agent/references/spec"
const OUT = ".agent/checklists/AUDIT_STATUS.md"

const comps = readdirSync(UI).filter((f) => f.endsWith(".tsx") && !f.endsWith(".stories.tsx")).map((f) => f.replace(/\.tsx$/, "")).sort()

// reference spec pages (case-insensitive match on kebab -> spec filename)
const specs = existsSync(SPEC) ? readdirSync(SPEC).filter((f) => f.endsWith(".dc.html")).map((f) => f.replace(/\.dc\.html$/, "").toLowerCase().replace(/[\s_]+/g, "-")) : []
const hasSpec = (n) => specs.includes(n)

// blast radius: how many component files import this one
const allSrc = comps.map((n) => ({ n, src: readFileSync(join(UI, `${n}.tsx`), "utf8") }))
const importCount = (name) => allSrc.filter((o) => o.n !== name && (o.src.includes(`/ui/${name}"`) || o.src.includes(`/ui/${name}'`) || new RegExp(`from ["'][^"']*/${name}["']`).test(o.src))).length

// static triage severity
let triage = {}
try {
  const raw = execSync(`node ${join(".agent/scripts/verify-audit.mjs")} --json`, { encoding: "utf8", maxBuffer: 32 * 1024 * 1024 })
  const j = JSON.parse(raw)
  for (const c of j.components) triage[c.name] = c.severity
} catch { /* triage optional */ }
const sevScore = { high: 2, medium: 1, low: 0, info: 0, clean: 0 }

// preserve prior results
const prior = {}
if (existsSync(OUT)) {
  for (const line of readFileSync(OUT, "utf8").split("\n")) {
    const m = line.match(/^\|\s*`?([a-z0-9-]+)`?\s*\|\s*(.*?)\|\s*$/)
    if (m && comps.includes(m[1])) prior[m[1]] = line
  }
}

const rows = comps.map((n) => {
  const ic = importCount(n)
  const score = (hasSpec(n) ? 3 : 0) + (ic >= 5 ? 2 : ic >= 1 ? 1 : 0) + (sevScore[triage[n]] || 0)
  return { n, ic, spec: hasSpec(n), sev: triage[n] || "?", score }
})
rows.sort((a, b) => b.score - a.score || b.ic - a.ic || a.n.localeCompare(b.n))

const reviewedCount = Object.values(prior).filter((l) => /\|\s*✅\s*\|/.test(l)).length
const now = execSync("git rev-parse --short HEAD", { encoding: "utf8" }).trim()

let md = `# AUDIT_STATUS.md — deep quality-audit tracker

> Generated by \`.agent/scripts/audit-queue.mjs\`. The recurring **AUDIT** loop
> (\`.agent/prompts/recurring-audit.md\`) works this queue **top-to-bottom** and
> updates each row **honestly** — a column is ✅ only if the check actually ran and
> passed this session (never mark PASS for a gate you didn't run; see AGENT.md §3).
>
> **Queue order = risk.** Components with a reference spec page, high blast radius
> (imported by many others), or static-triage findings are audited first.
> Do not re-audit a ✅-reviewed component unless a dependency it uses changed.

**Progress:** ${reviewedCount} / ${comps.length} reviewed  ·  library @ \`${now}\`

## Legend
- **Reviewed** — full audit pass completed (context, DS-compliance, visual, code, a11y, tests).
- **Issues** — issues were found (see the batch PR that resolved them).
- **Fixed** — all found issues resolved (or ⏳ = subjective calls queued for human confirmation).
- **DS ✓** — design-system compliant (tokens, theme, RTL, responsive, motion) — the highest bar.
- **Tests ✓** — story states covered + play/axe ran green in-browser this session.
- **Risk** — audit priority (⬆ higher first): spec page + blast radius + triage severity.

| Component | Reviewed | Issues | Fixed | DS ✓ | Tests ✓ | Risk | spec | imp | triage | Notes |
|-----------|:--------:|:------:|:-----:|:----:|:------:|:----:|:----:|:---:|:------:|-------|
`

for (const r of rows) {
  if (prior[r.n]) { md += prior[r.n] + "\n"; continue }
  md += `| \`${r.n}\` | ⬜ | — | — | — | — | ${r.score} | ${r.spec ? "◆" : ""} | ${r.ic} | ${r.sev} |  |\n`
}

writeFileSync(OUT, md)
console.log(`[audit-queue] wrote ${OUT} — ${comps.length} components, ${reviewedCount} already reviewed`)
console.log("top 12 by risk:")
for (const r of rows.slice(0, 12)) console.log(`  ${String(r.score).padStart(2)}  ${r.n}${r.spec ? " ◆spec" : ""}  imp=${r.ic}  triage=${r.sev}`)
