#!/usr/bin/env node
/**
 * build-fonts.mjs — generate the self-hosted type stack.
 *
 * AEGIS used to load its four families from a single Google Fonts `@import`
 * (15 static weights). That is a render-blocking third-party request, it is
 * unavailable under a strict CSP or in an air-gapped deployment — both
 * plausible for a security product — and hotlinking Google Fonts has been ruled
 * unlawful in Germany. For an Iranian company it is also simply liable to be
 * slow or blocked.
 *
 * This copies the needed woff2 out of the @fontsource packages into src/fonts/
 * and regenerates src/fonts.css from their own CSS, so the `unicode-range`
 * declarations are lifted verbatim rather than hand-transcribed (they are long
 * and drift silently when a font is updated).
 *
 * Deliberate subset choices:
 *   - latin + latin-ext for the three Latin faces. Dropping latin-ext would
 *     silently break Turkish, Polish and Czech text.
 *   - arabic ONLY for Vazirmatn. Its Latin block is its largest and is never
 *     used: Plex/Space Grotesk win for Latin runs in every AEGIS stack.
 *   - no italics — no AEGIS stack requests one.
 *   - IBM Plex Mono has NO variable release, so it ships static 400 + 600,
 *     the two weights the components actually use.
 *
 * Usage: node .agent/scripts/build-fonts.mjs
 */
import { readFileSync, writeFileSync, mkdirSync, copyFileSync, existsSync, rmSync } from "node:fs";
import { join } from "node:path";

const OUT_DIR = "src/fonts";
const OUT_CSS = "src/fonts.css";

/** family: the canonical name theme.css references (NOT fontsource's
 *  "… Variable" alias — we author our own @font-face, so we pick the name). */
const FACES = [
  {
    family: "Space Grotesk",
    pkg: "@fontsource-variable/space-grotesk",
    css: "wght.css",
    files: ["space-grotesk-latin-wght-normal.woff2", "space-grotesk-latin-ext-wght-normal.woff2"],
    variable: true,
  },
  {
    family: "IBM Plex Sans",
    pkg: "@fontsource-variable/ibm-plex-sans",
    css: "wght.css",
    files: ["ibm-plex-sans-latin-wght-normal.woff2", "ibm-plex-sans-latin-ext-wght-normal.woff2"],
    variable: true,
  },
  {
    family: "IBM Plex Mono",
    pkg: "@fontsource/ibm-plex-mono",
    css: "400.css",
    files: ["ibm-plex-mono-latin-400-normal.woff2", "ibm-plex-mono-latin-ext-400-normal.woff2"],
    variable: false,
  },
  {
    family: "IBM Plex Mono",
    pkg: "@fontsource/ibm-plex-mono",
    css: "600.css",
    files: ["ibm-plex-mono-latin-600-normal.woff2", "ibm-plex-mono-latin-ext-600-normal.woff2"],
    variable: false,
  },
  {
    family: "Vazirmatn",
    pkg: "@fontsource-variable/vazirmatn",
    css: "wght.css",
    files: ["vazirmatn-arabic-wght-normal.woff2"],
    variable: true,
  },
];

const field = (block, prop) => {
  const m = block.match(new RegExp(`${prop}:\\s*([^;]+)`));
  return m ? m[1].trim() : null;
};

let errors = 0;
const out = [];

out.push(`/* AEGIS type stack — SELF-HOSTED. No third-party requests.
 *
 * GENERATED by .agent/scripts/build-fonts.mjs — do not edit by hand.
 * Regenerate with \`npm run build:fonts\` after bumping a @fontsource package.
 *
 * Exported as \`@netbaan-project/ui/fonts.css\` and opt-in: import it only if you
 * want the bundled faces. Components reference the families through CSS
 * variables and fall back to system fonts when this is absent.
 *
 * Vazirmatn ships its ARABIC block only — Plex wins for Latin in every stack,
 * so its (large) Latin subset would never be used. See theme.css :lang(fa).
 */\n`);

rmSync(OUT_DIR, { recursive: true, force: true });
mkdirSync(OUT_DIR, { recursive: true });

for (const face of FACES) {
  const cssPath = join("node_modules", face.pkg, face.css);
  if (!existsSync(cssPath)) {
    console.error(`  MISSING ${cssPath} — is ${face.pkg} installed?`);
    errors++;
    continue;
  }
  const css = readFileSync(cssPath, "utf8");
  const blocks = [...css.matchAll(/@font-face\s*\{[^}]*\}/g)].map((m) => m[0]);

  for (const file of face.files) {
    const block = blocks.find((b) => b.includes(file));
    if (!block) {
      console.error(`  MISSING @font-face for ${file} in ${cssPath}`);
      errors++;
      continue;
    }
    const src = join("node_modules", face.pkg, "files", file);
    if (!existsSync(src)) {
      console.error(`  MISSING ${src}`);
      errors++;
      continue;
    }
    copyFileSync(src, join(OUT_DIR, file));

    const weight = field(block, "font-weight");
    const range = field(block, "unicode-range");
    const format = face.variable ? "woff2-variations" : "woff2";

    out.push(`@font-face {
  font-family: "${face.family}";
  font-style: normal;
  font-weight: ${weight};
  font-display: swap;
  src: url("./fonts/${file}") format("${format}");${range ? `\n  unicode-range: ${range};` : ""}
}\n`);
  }
}

if (errors) {
  console.error(`\nFONT BUILD FAILED — ${errors} missing file(s)/block(s).`);
  process.exit(1);
}

writeFileSync(OUT_CSS, out.join("\n"));
const faceCount = out.length - 1;
console.log(`Wrote ${OUT_CSS} — ${faceCount} @font-face rule(s), files in ${OUT_DIR}/`);
