#!/usr/bin/env node
// Phase 2: analyze component exports and generate the public barrel `src/index.ts`.
//
// Run `node .agent/scripts/build-barrel.mjs --check` to report cross-file name
// collisions without writing. Run without --check to (re)generate the barrel.
//
// Strategy: flat named re-exports (Ant-style `import { Button } from '@netbaan/ui'`).
// Value and type exports are parsed per file; collisions are reported so they can
// be resolved deliberately rather than silently shadowed by `export *`.

import { readdirSync, readFileSync, writeFileSync, statSync } from "node:fs";
import { join } from "node:path";

const UI_DIR = "src/components/ui";
const check = process.argv.includes("--check");

// Deliberate aliases for known cross-file name collisions. The bare name is kept
// by the alphabetically-first module; the other module re-exports under an alias.
// A NEW, unlisted collision makes generation fail loudly (see below) so duplicates
// are resolved on purpose, never silently shadowed.
const ALIASES = {
  "form-provider": { FormActions: "FormProviderActions" },
};

const isComponent = (n) =>
  n.endsWith(".tsx") && !n.endsWith(".stories.tsx") && !n.endsWith(".test.tsx");

// Parse the export names from a source file. Returns {values:[], types:[]}.
// Handles single declarations and `export { ... }` / `export type { ... }`
// blocks, including multiline blocks ([^}] spans newlines).
function parseExports(src) {
  const values = new Set();
  const types = new Set();
  for (const m of src.matchAll(/^export\s+(?:const|function|class|abstract class)\s+([A-Za-z0-9_]+)/gm))
    values.add(m[1]);
  for (const m of src.matchAll(/^export\s+type\s+([A-Za-z0-9_]+)\s*[=<]/gm)) types.add(m[1]);
  for (const m of src.matchAll(/export\s+(type\s+)?\{([^}]*)\}/g)) {
    const blockIsType = !!m[1];
    for (const part of m[2].split(",")) {
      const raw = part.trim();
      if (!raw) continue;
      const isType = blockIsType || /^type\s/.test(raw);
      const name = raw.replace(/^type\s+/, "").split(/\s+as\s+/).pop().trim();
      if (name) (isType ? types : values).add(name);
    }
  }
  return { values: [...values], types: [...types] };
}

const files = readdirSync(UI_DIR)
  .filter((n) => statSync(join(UI_DIR, n)).isFile() && isComponent(n))
  .sort();

const owners = new Map(); // name -> [modules]
const perFile = [];
for (const name of files) {
  const mod = name.replace(/\.tsx$/, "");
  const { values, types } = parseExports(readFileSync(join(UI_DIR, name), "utf8"));
  perFile.push({ mod, values, types });
  for (const n of [...values, ...types]) {
    if (!owners.has(n)) owners.set(n, []);
    owners.get(n).push(mod);
  }
}

const collisions = [...owners.entries()].filter(([, mods]) => mods.length > 1);
console.log(`Scanned ${files.length} component files.`);
console.log(`Distinct exported names: ${owners.size}`);
console.log(`Collisions (same name, multiple files): ${collisions.length}`);
for (const [name, mods] of collisions) console.log(`  ${name}  <-  ${mods.join(", ")}`);

// A collision is "handled" if exactly one owner keeps the bare name and every
// other owner has an alias listed in ALIASES.
const unhandled = collisions.filter(([name, mods]) => {
  const owner = [...mods].sort()[0];
  return mods.some((m) => m !== owner && !ALIASES[m]?.[name]);
});

if (check) process.exit(0);

if (unhandled.length) {
  console.error("\nUnhandled collisions — add an alias to ALIASES in this script:");
  for (const [name, mods] of unhandled) console.error(`  ${name}  <-  ${mods.join(", ")}`);
  process.exit(1);
}

// Modules that must re-export explicitly (because they alias a colliding name);
// all others can use `export *`.
const aliasedMods = new Set(Object.keys(ALIASES));

function emit({ mod, values, types }) {
  const path = `./components/ui/${mod}`;
  if (!aliasedMods.has(mod)) return `export * from "${path}";`;
  const aliasMap = ALIASES[mod] || {};
  const ren = (n) => (aliasMap[n] ? `${n} as ${aliasMap[n]}` : n);
  const lines = [];
  if (values.length) lines.push(`export { ${values.map(ren).join(", ")} } from "${path}";`);
  if (types.length) lines.push(`export type { ${types.map(ren).join(", ")} } from "${path}";`);
  return lines.join("\n");
}

const header = `// AUTO-GENERATED by .agent/scripts/build-barrel.mjs — do not edit by hand.
// Public API surface of @netbaan/ui. Regenerate after adding/removing components.
`;
const body = perFile.map(emit).join("\n");
// Root-level (non-ui) public exports.
const extras = `export { ThemeProvider, useTheme } from "./components/theme-provider";`;
writeFileSync("src/index.ts", `${header}\n${extras}\n\n${body}\n`, "utf8");
console.log(`\nWrote src/index.ts (${perFile.length} modules).`);
